BEGIN;
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `lastname` VARCHAR(100) DEFAULT NULL,
	`firstname`
	`email` VARCHAR (100) DEFAULT NULL,
	`status` TINYINT DEFAULT 0,
	`created_at` TEXT DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
